name: Chrome Extension Deploy

on:
  push:
    branches:
      - main

jobs:
  setup:
    name: Setup environment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install NVM
        run: |
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
          nvm install

      - name: Enable Corepack
        run: corepack enable

      - name: Use pnpm
        run: corepack prepare pnpm --activate

      - name: Install dependencies
        run: pnpm install

      - name: Cache Node.js, PNPM, and dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.nvm
            ~/.pnpm-store
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('.nvmrc') }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ hashFiles('.nvmrc') }}-pnpm-

  release:
    name: Bump version and release
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.nvm
            ~/.pnpm-store
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('.nvmrc') }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-node

      - name: Set up git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Run release script
        run: |
          pnpm release
          git push --follow-tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    name: Build and pack
    runs-on: ubuntu-latest
    needs:
      - setup
      - release

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.nvm
            ~/.pnpm-store
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('.nvmrc') }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-node

      - name: Build extension
        run: pnpm build

      - name: Zip the extension
        run: zip -r extension.zip dist

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: extension
          path: extension.zip

  upload_and_publish:
    name: Upload & publish
    runs-on: ubuntu-latest
    needs:
      - build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: extension
          path: .

      - name: Upload & release the extension
        uses: mnao305/chrome-extension-upload@v5.0.0
        with:
          file-path: extension.zip
          extension-id: cbmkpmahhohcoocponpomeegpdlhlmim
          client-id: ${{ secrets.CLIENT_ID }}
          client-secret: ${{ secrets.CLIENT_SECRET }}
          refresh-token: ${{ secrets.REFRESH_TOKEN }}
